<?php
class InvoiceController extends PageController { private PDO $db; public function __construct(){parent::__construct();$this->db=Database::getInstance();}
 private function auth(): bool { if(!isset($_SESSION['user_id'])){$this->redirect('auth/login');return false;} return true; }
 public function action_list(): void { if(!$this->auth())return; $page=max(1,(int)$this->request->get('page',1));$per=10;$total=(int)$this->db->query('SELECT COUNT(*) FROM invoices')->fetchColumn();$stmt=$this->db->prepare('SELECT invoices.*, users.email AS user_email, products.name AS product_name FROM invoices JOIN users ON users.id=invoices.user_id JOIN products ON products.id=invoices.product_id ORDER BY invoices.id DESC LIMIT :l OFFSET :o');$stmt->bindValue(':l',$per,PDO::PARAM_INT);$stmt->bindValue(':o',($page-1)*$per,PDO::PARAM_INT);$stmt->execute();$this->render('invoice/list',['invoices'=>$stmt->fetchAll(),'page'=>$page,'pages'=>max(1,ceil($total/$per))],__('invoices')); }
 public function action_create(): void { $this->form('create'); }
 public function action_edit(): void { $this->form('edit'); }
 private function form(string $mode): void { if(!$this->auth())return; $id=(int)$this->request->get('id',0);$item=['invoice_date'=>date('Y-m-d'),'quantity'=>1]; if($mode==='edit'){ $st=$this->db->prepare('SELECT * FROM invoices WHERE id=:id');$st->execute([':id'=>$id]);$item=$st->fetch(); if(!$item){$this->redirect('invoice/list');return;}} $errors=[]; if($this->request->isPost()){ $data=$this->request->allPost();$errors=StoreInvoiceRequest::validate($data); if(!$errors){ $p=$this->db->prepare('SELECT price FROM products WHERE id=:id');$p->execute([':id'=>(int)$data['product_id']]);$price=(float)$p->fetchColumn();$total=$price*(int)$data['quantity']; if($mode==='create'){$sql='INSERT INTO invoices(user_id,product_id,invoice_date,quantity,total_amount) VALUES(:user_id,:product_id,:invoice_date,:quantity,:total_amount)';$params=[];} else {$sql='UPDATE invoices SET user_id=:user_id,product_id=:product_id,invoice_date=:invoice_date,quantity=:quantity,total_amount=:total_amount WHERE id=:id';$params=[':id'=>$id];} $params += [':user_id'=>(int)$data['user_id'],':product_id'=>(int)$data['product_id'],':invoice_date'=>$data['invoice_date'],':quantity'=>(int)$data['quantity'],':total_amount'=>$total]; $this->db->prepare($sql)->execute($params);$_SESSION['flash_success']=__('success_saved');$this->redirect('invoice/list');return;} $item=array_merge($item,$data);} $users=$this->db->query('SELECT id,email,first_name,last_name FROM users ORDER BY email')->fetchAll();$products=$this->db->query('SELECT id,name,price FROM products ORDER BY name')->fetchAll();$this->render('invoice/form',['errors'=>$errors,'item'=>$item,'mode'=>$mode,'users'=>$users,'products'=>$products],($mode==='create'?__('create'):__('edit')).' '.__('invoices')); }
 public function action_delete(): void { if(!$this->auth())return; if($this->request->isPost()){$this->db->prepare('DELETE FROM invoices WHERE id=:id')->execute([':id'=>(int)$this->request->post('id',0)]);$_SESSION['flash_success']=__('success_deleted');}$this->redirect('invoice/list');}
}
