<?php
class ProductController extends PageController {
    private PDO $db; private string $uploadDir;
    public function __construct(){ parent::__construct(); $this->db=Database::getInstance(); $this->uploadDir=DATA_DIR.'/uploads/products'; if(!is_dir($this->uploadDir)) mkdir($this->uploadDir,0755,true); }
    private function auth(): bool { if(!isset($_SESSION['user_id'])){ $this->redirect('auth/login'); return false;} return true; }
    public function action_list(): void { if(!$this->auth()) return; $page=max(1,(int)$this->request->get('page',1)); $per=10; $total=(int)$this->db->query('SELECT COUNT(*) FROM products')->fetchColumn(); $stmt=$this->db->prepare('SELECT * FROM products ORDER BY id DESC LIMIT :l OFFSET :o'); $stmt->bindValue(':l',$per,PDO::PARAM_INT); $stmt->bindValue(':o',($page-1)*$per,PDO::PARAM_INT); $stmt->execute(); $this->render('product/list',['products'=>$stmt->fetchAll(),'page'=>$page,'pages'=>max(1,ceil($total/$per))],__('products')); }
    public function action_show(): void { if(!$this->auth()) return; $id=(int)$this->request->get('id',0); $stmt=$this->db->prepare('SELECT * FROM products WHERE id=:id'); $stmt->execute([':id'=>$id]); $product=$stmt->fetch(); if(!$product){$this->redirect('product/list');return;} $this->render('product/show',['product'=>$product],$product['name']); }
    public function action_create(): void { if(!$this->auth()) return; $errors=[]; $old=[]; if($this->request->isPost()){ $old=$this->request->allPost(); $errors=StoreProductRequest::validate($old,$_FILES['image']??[]); if(!$errors){ $image=$this->upload($_FILES['image']??[]); $stmt=$this->db->prepare('INSERT INTO products(name,category,price,description,image) VALUES(:name,:category,:price,:description,:image)'); $stmt->execute([':name'=>trim($old['name']),':category'=>$old['category'],':price'=>(float)$old['price'],':description'=>trim($old['description']??''),':image'=>$image]); $_SESSION['flash_success']=__('success_saved'); $this->redirect('product/list'); return; }} $this->render('product/form',['errors'=>$errors,'item'=>$old,'mode'=>'create'],__('create').' '.__('products')); }
    public function action_edit(): void { if(!$this->auth()) return; $id=(int)$this->request->get('id',0); $stmt=$this->db->prepare('SELECT * FROM products WHERE id=:id'); $stmt->execute([':id'=>$id]); $item=$stmt->fetch(); if(!$item){$this->redirect('product/list');return;} $errors=[]; if($this->request->isPost()){ $data=$this->request->allPost(); $errors=StoreProductRequest::validate($data,$_FILES['image']??[]); if(!$errors){ $image=$this->upload($_FILES['image']??[]) ?: $item['image']; $stmt=$this->db->prepare('UPDATE products SET name=:name,category=:category,price=:price,description=:description,image=:image WHERE id=:id'); $stmt->execute([':name'=>trim($data['name']),':category'=>$data['category'],':price'=>(float)$data['price'],':description'=>trim($data['description']??''),':image'=>$image,':id'=>$id]); $_SESSION['flash_success']=__('success_saved'); $this->redirect('product/list'); return;} $item=array_merge($item,$data);} $this->render('product/form',['errors'=>$errors,'item'=>$item,'mode'=>'edit'],__('edit').' '.__('products')); }
    public function action_delete(): void { if(!$this->auth()) return; if($this->request->isPost()){ $id=(int)$this->request->post('id',0); $stmt=$this->db->prepare('DELETE FROM products WHERE id=:id'); $stmt->execute([':id'=>$id]); $_SESSION['flash_success']=__('success_deleted'); } $this->redirect('product/list'); }
    private function upload(array $file): string { if(empty($file['tmp_name'])||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK) return ''; $ext=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION)); if(!in_array($ext,['jpg','jpeg','png','gif','webp'],true)) return ''; $name=time().'_'.bin2hex(random_bytes(4)).'.'.$ext; move_uploaded_file($file['tmp_name'],$this->uploadDir.'/'.$name); return 'data/uploads/products/'.$name; }
}
