<?php
class UserController extends PageController { private PDO $db; public function __construct(){parent::__construct();$this->db=Database::getInstance();}
 private function auth(): bool { if(!isset($_SESSION['user_id'])){$this->redirect('auth/login');return false;} return true; }
 public function action_list(): void { if(!$this->auth())return; $page=max(1,(int)$this->request->get('page',1));$per=10;$total=(int)$this->db->query('SELECT COUNT(*) FROM users')->fetchColumn();$stmt=$this->db->prepare('SELECT * FROM users ORDER BY id DESC LIMIT :l OFFSET :o');$stmt->bindValue(':l',$per,PDO::PARAM_INT);$stmt->bindValue(':o',($page-1)*$per,PDO::PARAM_INT);$stmt->execute();$this->render('user/list',['users'=>$stmt->fetchAll(),'page'=>$page,'pages'=>max(1,ceil($total/$per))],__('users')); }
 public function action_create(): void { if(!$this->auth())return; $errors=[];$item=[]; if($this->request->isPost()){ $item=$this->request->allPost();$errors=StoreUserRequest::validate($item,true); if(!$errors){ $name=trim($item['name']); [$first,$last]=array_pad(explode(' ',$name,2),2,''); $stmt=$this->db->prepare('INSERT INTO users(login,password,email,first_name,last_name,phone,city,gender,about,role,age) VALUES(:login,:password,:email,:first,:last,:phone,"","","",:role,:age)'); $stmt->execute([':login'=>$item['email'],':password'=>password_hash($item['password'],PASSWORD_DEFAULT),':email'=>$item['email'],':first'=>$first,':last'=>$last,':phone'=>$item['phone']??'',':role'=>$item['role']??'user',':age'=>$item['age']!==''?(int)$item['age']:null]); $this->sendUserCreatedMail($item['email'],$name); $_SESSION['flash_success']=__('success_saved');$this->redirect('user/list');return; }} $this->render('user/form',['errors'=>$errors,'item'=>$item,'mode'=>'create'],__('create').' '.__('users')); }
 public function action_edit(): void { if(!$this->auth())return; $id=(int)$this->request->get('id',0);$stmt=$this->db->prepare('SELECT *, (first_name||" "||last_name) AS name FROM users WHERE id=:id');$stmt->execute([':id'=>$id]);$item=$stmt->fetch(); if(!$item){$this->redirect('user/list');return;} $errors=[]; if($this->request->isPost()){ $data=$this->request->allPost();$errors=StoreUserRequest::validate($data,false); if(!$errors){ [$first,$last]=array_pad(explode(' ',trim($data['name']),2),2,''); $sql='UPDATE users SET login=:login,email=:email,first_name=:first,last_name=:last,phone=:phone,role=:role,age=:age'.(($data['password']??'')!==''?',password=:password':'').' WHERE id=:id'; $params=[':login'=>$data['email'],':email'=>$data['email'],':first'=>$first,':last'=>$last,':phone'=>$data['phone']??'',':role'=>$data['role']??'user',':age'=>$data['age']!==''?(int)$data['age']:null,':id'=>$id]; if(($data['password']??'')!=='')$params[':password']=password_hash($data['password'],PASSWORD_DEFAULT); $this->db->prepare($sql)->execute($params); $_SESSION['flash_success']=__('success_saved');$this->redirect('user/list');return;} $item=array_merge($item,$data);} $this->render('user/form',['errors'=>$errors,'item'=>$item,'mode'=>'edit'],__('edit').' '.__('users')); }
 public function action_delete(): void { if(!$this->auth())return; if($this->request->isPost()){ $stmt=$this->db->prepare('DELETE FROM users WHERE id=:id');$stmt->execute([':id'=>(int)$this->request->post('id',0)]);$_SESSION['flash_success']=__('success_deleted');} $this->redirect('user/list'); }
 private function sendUserCreatedMail(string $email,string $name): void { $dir=ROOT_DIR.'/storage/mailtrap'; if(!is_dir($dir)) mkdir($dir,0755,true); file_put_contents($dir.'/'.date('Ymd_His').'_user_created.eml',"To: $email\nSubject: Welcome to Space Engine\n\nHello, $name! Your account has been created.\n"); }
}
